name: GitHub Actions Demo
on: [push]
jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Job was triggered by ${{ github.event_name }}."
    - run: echo "This is running on ${{ runner.os }} server hosted by GitHub."
    - run: echo "branch: ${{ github.ref }}"
    - run: echo "repo: ${{ github.repository }}"
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "${{ github.repository }} has been cloned."
    - name: List files in repo
      run: |
        ls ${{ github.workspace }}
    - run: echo "The job status is ${{ job.status }}."
